# Generated by Django 5.0.6 on 2024-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tag', '0001_initial'),
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='app_tag.tag'),
        ),
    ]
