# Generated by Django 5.0.6 on 2024-07-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_alter_task_assignee_alter_task_labels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='executor',
        ),
    ]
