# Generated by Django 5.0.6 on 2024-07-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_rename_assignee_task_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='labels',
            new_name='label',
        ),
    ]
