# Generated by Django 5.0.6 on 2024-07-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_rename_labels_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
