# Generated by Django 5.0.6 on 2024-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_rename_title_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
